data_type_list = {"VALUE", "SERIAL", "BLANK", "FROM_TABLE", "RANDOM_FROM_TABLE", "NULL", "ZERO", "ONE", "RANDOM", "ZERO_PADDED", \
"RANDOM_ZERO_PADDED", "DECIMAL", "RANDOM_PRICE", "LIST_ORD", "LIST_RAND", "ENUM", "PREVIOUS", "COPY", "ID", "USERNAME", "PASSWORD_RANDOM", \
"PASSWORD_HASH", "NAME_FAMILY", "NAME_FIRST","NAME_FULL", "NAME_FAMILY_KN", "NAME_FIRST_KN", "NAME_FULL_KN", \
"NAME_FAMILY_EN", "NAME_FIRST_EN", "NAME_FULL_EN","DATE_OF_BIRTH", "AGE", "SEX", "SEX_AS_NUM", "ADDRESS_ZIP", \
"ADDRESS_FULL", "ADDRESS_COUNTRY", "ADDRESS_PREFECTURE", "ADDRESS_CITY", "ADDRESS_CHOME", "ADDRESS_BANCHI", \
"ADDRESS_NUMBER", "ADDRESS_BUILDING", "ADDRESS_ROOM_NO", "PHONE_HOME", "PHONE_WORK", "PHONE_MOBILE", "EMAIL_WORK", \
"EMAIL_PERSONAL", "PROFESSION", "NATIONALITY", "COMPANY_NAME", "COMPANY_ROLE", "COMPANY_DIVISION", "INDUSTRY", \
"TIMESTAMP", "TIMESTAMP_NOW", "TIMESTAMP_TODAY", "TIMESTAMP_DATE", "TIMESTAMP_SECONDS", "TIMESTAMP_MILLIS", "USER_AGENT", "IP_ADDRESS"}