PREGENERATED_DATA = "./functions/data/userlocal.csv"

REQUIRES_USER_DATA = {"USERNAME", "PASSWORD", "NAME_FAMILY", "NAME_FIRST", \
        "NAME_FULL", "NAME_FAMILY_KN", "NAME_FIRST_KN", "NAME_FULL_KN", "NAME_FAMILY_EN", "NAME_FIRST_EN", "NAME_FULL_EN", \
        "DATE_OF_BIRTH", "AGE", "SEX", "SEX_AS_NUM", "ADDRESS_ZIP", "ADDRESS_FULL", "ADDRESS_COUNTRY", "ADDRESS_PREFECTURE", \
        "ADDRESS_CITY", "ADDRESS_CHOME", "ADDRESS_BANCHI", "ADDRESS_NUMBER", "ADDRESS_BUILDING", "ADDRESS_ROOM_NO", \
        "PHONE_HOME", "PHONE_WORK", "PHONE_MOBILE", "EMAIL_WORK", "EMAIL_PERSONAL", "PROFESSION", "NATIONALITY", \
        "COMPANY_NAME", "COMPANY_ROLE", "COMPANY_DIVISION", "INDUSTRY"}

DAYS_IN_YEAR = 365
DAYS_IN_MONTH = 30
HOURS_IN_DAY = 24
MINS_IN_HOUR= 60
SECONDS_IN_MIN = 60
MILLIS_IN_SECOND = 1000
TIMESTAMP_WITH_MICROS='%Y-%m-%d %H:%M:%S.%f'
TIMESTAMP_WITH_SECONDS='%Y-%m-%d %H:%M:%S'
TIMESTAMP_DATE='%Y-%m-%d'