PREGENERATED_DATA = "./functions/data/userlocal.csv"

DAYS_IN_YEAR = 365
DAYS_IN_MONTH = 30
HOURS_IN_DAY = 24
MINS_IN_HOUR= 60
SECONDS_IN_MIN = 60
MILLIS_IN_SECOND = 1000
TIMESTAMP_WITH_MICROS='%Y-%m-%d %H:%M:%S.%f'
TIMESTAMP_WITH_SECONDS='%Y-%m-%d %H:%M:%S'
TIMESTAMP_DATE='%Y-%m-%d'